"""Render a fast camera-specific preview using the independent bootstrap detector.

This file is for geometry/count validation only. The final submission video should be generated by
`DETECTOR_BACKEND=mmdet` after training the RTMDet checkpoint.
"""
from __future__ import annotations

import argparse
import time

import cv2
import numpy as np

SRC = np.float32([[313,53],[373,53],[210,359],[27,359]])
DST = np.float32([[0,0],[249,0],[249,599],[0,599]])
M = cv2.getPerspectiveTransform(SRC,DST)
INV = np.linalg.inv(M)


def detect_and_score(frame: np.ndarray):
    warped=cv2.warpPerspective(frame,M,(250,600))
    hsv=cv2.cvtColor(warped,cv2.COLOR_BGR2HSV)
    band=hsv[400:440,25:225]
    score=float(np.mean((band[:,:,2]>145)&(band[:,:,1]<150)))
    mask=((hsv[:,:,2]>145)&(hsv[:,:,1]<155)).astype(np.uint8)*255
    mask[:,:12]=0;mask[:,238:]=0;mask[:18]=0;mask[580:]=0
    mask=cv2.morphologyEx(mask,cv2.MORPH_CLOSE,np.ones((7,7),np.uint8),iterations=2)
    mask=cv2.morphologyEx(mask,cv2.MORPH_OPEN,np.ones((7,7),np.uint8),iterations=1)
    cnts,_=cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    boxes=[]
    for c in cnts:
        area=cv2.contourArea(c);x,y,bw,bh=cv2.boundingRect(c);fill=area/max(bw*bh,1)
        if area<700 or bw<70 or bh<18 or bh>220 or fill<.18: continue
        pts=np.float32([[[x,y],[x+bw,y],[x+bw,y+bh],[x,y+bh]]])
        q=cv2.perspectiveTransform(pts,INV)[0]
        x1=max(0,int(q[:,0].min()));y1=max(0,int(q[:,1].min()));x2=min(639,int(q[:,0].max()));y2=min(359,int(q[:,1].max()))
        boxes.append((x1,y1,x2,y2))
    return score,boxes


def main():
    ap=argparse.ArgumentParser();ap.add_argument('video');ap.add_argument('output');args=ap.parse_args()
    cap=cv2.VideoCapture(args.video)
    fps=cap.get(cv2.CAP_PROP_FPS) or 25; total=int(cap.get(cv2.CAP_PROP_FRAME_COUNT));w=int(cap.get(cv2.CAP_PROP_FRAME_WIDTH));h=int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    if (w,h)!=(640,360): raise SystemExit('Preview calibration expects 640x360 input.mp4')
    writer=cv2.VideoWriter(args.output,cv2.VideoWriter_fourcc(*'mp4v'),fps,(w,h))
    count=0;active=False;hi=0;lo=0;boxes=[];score=0.0;idx=0;started=time.perf_counter()
    roi=np.array([[313,53],[373,53],[210,359],[27,359]],np.int32)
    line_a=(189,186);line_b=(302,186)
    while True:
        ok,frame=cap.read()
        if not ok: break
        if idx%5==0:
            score,boxes=detect_and_score(frame)
            if not active:
                hi = hi + 1 if score>.30 else 0
                if hi>=2:
                    count+=1;active=True;hi=0;lo=0
            else:
                lo = lo + 1 if score<=.30 else 0
                if lo>=1:
                    active=False;lo=0;hi=0
        cv2.polylines(frame,[roi],True,(165,165,165),1,cv2.LINE_AA)
        cv2.line(frame,line_a,line_b,(0,220,255),3,cv2.LINE_AA)
        for x1,y1,x2,y2 in boxes:
            cv2.rectangle(frame,(x1,y1),(x2,y2),(40,210,40),2,cv2.LINE_AA)
        overlay=frame.copy();cv2.rectangle(overlay,(12,12),(316,111),(12,12,12),-1);cv2.addWeighted(overlay,.72,frame,.28,0,frame)
        cv2.putText(frame,f'REFERENCE COUNT: {count}',(24,43),cv2.FONT_HERSHEY_SIMPLEX,.72,(255,255,255),2,cv2.LINE_AA)
        cv2.putText(frame,'BOOTSTRAP PREVIEW - NOT MMDETECTION',(24,69),cv2.FONT_HERSHEY_SIMPLEX,.42,(210,210,210),1,cv2.LINE_AA)
        cv2.putText(frame,f'line signal: {score:.2f}',(24,92),cv2.FONT_HERSHEY_SIMPLEX,.42,(210,210,210),1,cv2.LINE_AA)
        writer.write(frame);idx+=1
        if idx%2500==0: print(f'{idx/max(total,1)*100:.0f}% count={count} speed={idx/max(time.perf_counter()-started,1e-6):.1f} fps')
    cap.release();writer.release();print('final_count',count,'frames',idx)

if __name__=='__main__': main()
